# Copyright © 2024 Novobi, LLC
# See LICENSE file for full copyright and licensing details.

{
    'name': 'LiveAg: Consignment Management',
    'summary': '',
    'author': 'Novobi',
    'website': 'https://www.novobi.com/',
    'category': 'Consignment/Consignment',
    'version': '19.0.1.0.9',
    'license': 'OPL-1',
    'depends': [
        'base_setup', 'mail', 'contacts','uom'
    ],
    'data': [
        # ============================== DATA =================================
        'data/ir_sequence_data.xml',
        'data/consignment_contract_actions.xml',
        'data/email_templates.xml',
        'data/ir_module_category_data.xml',
        # ============================== SECURITY =============================
        'security/res_groups.xml',
        'security/consignment_contract_security.xml',
        'security/ir.model.access.csv',
        # ============================== REPORT ===============================
        'report/consignment_contract_templates.xml',
        'report/consignment_contract_reports.xml',
        'report/auction_templates.xml',
        'report/auction_reports.xml',
        'report/buyer_invoice_template.xml',
        'report/buyer_invoice_reports.xml',
        # ============================== VIEWS ================================
        'views/sale_type_views.xml',
        'views/contract_type_views.xml',
        'views/kind_list_views.xml',
        'views/slide_type_views.xml',
        'views/weight_stop_views.xml',
        'views/origin_list_views.xml',
        'views/frame_size_views.xml',
        'views/flesh_type_views.xml',
        'views/weight_variance_views.xml',
        'views/horns_list_views.xml',
        'views/bangs_vaccinated_views.xml',
        'views/special_section_views.xml',
        'views/genetic_merit_views.xml',
        'views/location_type_views.xml',
        'views/whose_option_views.xml',
        'views/implanted_list_views.xml',
        'views/castration_list_views.xml',
        'views/third_party_age_views.xml',
        'views/vac_program_views.xml',
        'views/sale_auction_views.xml',
        # 'views/consignment_contract_views.xml',
        'views/premium_genetics_program_views.xml',
        'views/van_program_views.xml',
        'views/gap_program_views.xml',
        'views/res_region_views.xml',
        'views/contract_activity_log_views.xml',
        'views/program_icon_views.xml',
        'views/beef_checkoff_views.xml',
        'views/auction_report_email_views.xml',
        # 'views/res_users_views.xml',
        # ============================== WIZARDS ==============================
        'wizard/split_contract_wizard.xml',
        'wizard/buyer_report_wizard_views.xml',
        'wizard/seller_report_wizard_views.xml',
        'wizard/rep_report_wizard_views.xml',
        'wizard/buyer_invoice_wizard_views.xml',
        'wizard/delivery_sheet_wizard_views.xml',
        'wizard/merge_option_contracts.xml',
        'wizard/merge_deliveries.xml',
        'wizard/buyer_email_send_wizard_views.xml',
        'wizard/seller_email_send_wizard_views.xml',
        'wizard/rep_email_send_wizard_views.xml',
        # ============================== VIEWS (CONT) =====================
        'views/delivery_views.xml',
        'views/liveag_consignment_menus.xml',
        'views/sale_auction_menus.xml',
        # 'views/res_partner.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'liveag_consignment/static/src/css/style.css',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init',
}
