# Copyright © 2024 Novobi, LLC
# See LICENSE file for full copyright and licensing details.

# Custom Odoo models
from . import sale_type
from . import contract_type
from . import kind_list
from . import slide_type
from . import weight_stop
from . import origin_list
from . import frame_size
from . import flesh_type
from . import weight_variance
from . import horns_list
from . import bangs_vaccinated
from . import special_section
from . import genetic_merit
from . import location_type
from . import whose_option
from . import implanted_list
from . import castration_list
from . import third_party_age
from . import vac_program
from . import sale_auction
from . import premium_genetics_program
from . import van_program
from . import gap_program
from . import consignment_contract
from . import consignment_catalog_change
from . import res_rep
from . import res_contact_type
from . import buyer_number
from . import draft
from . import contract_deduction
from . import contract_activity_log
from . import contract_addendum
from . import program_icon
from . import delivery_weight_mixin
from . import delivery_slide_mixin
from . import beef_checkoff
from . import delivery_financial_mixin
from . import delivery_monetary
from . import delivery
from . import delivery_line
from . import delivery_check
from . import delivery_adjustment
# Base Odoo models
from . import res_country_state
from . import res_partner
from . import res_partner_email
from . import res_region
from . import auth_token
from . import ir_http
from . import auction_report_email
from . import res_users
